---
abstract: 'Stuff I always use'
author:
  - 'John Napiorkowski C< <<jjnapiork@cpan.org>> >'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Task::BeLike::JJNAPIORK
name: Task-BeLike-JJNAPIORK
no_index:
  directory:
    - inc
    - t
requires:
  App::Ack: 1.92
  App::cpanminus: 1.0012
  App::local::lib::helper: 0.02
  Module::Install: 1.00
  Module::Install::AuthorTests: 0.002
  Module::Install::AutoManifest: 0.003
  Module::Install::GithubMeta: 0.10
  Module::Install::ManifestSkip: 0.12
  Module::Install::ReadmeFromPod: 0.12
  Module::Install::ReadmePodFromPod: 0.01
  Module::Setup: 0.09
  perl: 5.8.8
resources:
  homepage: http://github.com/jjn1056/Task-BeLike-JJNAPIORK/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Task-BeLike-JJNAPIORK.git
version: 0.03
